fullnameOverride: youtube-service-prod

deployment:
  enabled: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

replicaCount: 1

image:
  repository: ghcr.io/donghun0508/youtube-service
  tag: acc4abd475b2a7e4cdeee352011add53420fb941
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: false

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0"

monitoring:
  enabled: true
  namespace: prometheus
  labels:
    release: prometheus
  path: /actuator/prometheus
  interval: 15s
  portName: http
