fullnameOverride: api-gateway

replicaCount: 1

image:
  repository: ghcr.io/donghun0508/api-gateway
  tag: 82574a9a62a31028cbffa2b836709a5eb13ea7c8
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: true
  className: traefik
  host: api.codecrew.site
  path: /
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: api-gateway-transport@kubernetescrd
  tls: []

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

monitoring:
  enabled: true
  namespace: prometheus
  labels:
    release: prometheus
  path: /actuator/prometheus
  interval: 15s
  portName: http
