apiVersion: v1
kind: ConfigMap
metadata:
  name: member-service-prod
  namespace: member-service-prod
  labels:
    app.kubernetes.io/name: member-service-prod
    app.kubernetes.io/instance: member-service-prod
data:
  SERVER_PORT: "8080"
  MANAGEMENT_PORT: "8080"