fullnameOverride: member-service

replicaCount: 1

image:
  repository: ghcr.io/donghun0508/member-service
  tag: 4f8fc59d5759c55f324d539a9b65c6d77b152a5a
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: false

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

monitoring:
  enabled: true
  namespace: prometheus
  labels:
    release: prometheus
  path: /actuator/prometheus
  interval: 15s
  portName: http
