fullnameOverride: member-service-prod

replicaCount: 1

image:
  repository: ghcr.io/donghun0508/member-service
  tag: 1da17ab35df2996edd491ea89834f0b4b9f3da80
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: false

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

monitoring:
  enabled: true
  namespace: prometheus
  labels:
    release: prometheus
  path: /actuator/prometheus
  interval: 15s
  portName: http
