grafana:
  service:
    type: NodePort
    nodePort: 31000
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.codecrew.site
    path: /
    pathType: Prefix

prometheusOperator:
  admissionWebhooks:
    enabled: false