agones:
  allocator:
    install: true
    service:
      http:
        responsePort: 8080
    serviceMetrics:
      http:
        enabled: true
        port: 8080
        portName: http
  ping:
    install: true
