agones:
  allocator:
    install: true
    healthCheck:
      initialDelaySeconds: 10
      periodSeconds: 3
      failureThreshold: 3
      timeoutSeconds: 1
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 3
      failureThreshold: 3
    service:
      serviceType: ClusterIP
    serviceMetrics:
      http:
        enabled: true
        port: 8080
        portName: http
  ping:
    install: false
