apiVersion: v1
kind: ConfigMap
metadata:
  name: world-master-service-prod
  namespace: world-master-service-prod
  labels:
    app.kubernetes.io/name: world-master-service-prod
    app.kubernetes.io/instance: world-master-service-prod
data:
  SERVER_PORT: "8080"
  MANAGEMENT_PORT: "8080"