fullnameOverride: world-master-service-prod

deployment:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

replicaCount: 1

image:
  repository: ghcr.io/donghun0508/world-master-service
  tag: 889601e26b701f777d12ca32492c7ce499c73e1c
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: false

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0"

monitoring:
  enabled: true
  namespace: prometheus
  labels:
    release: prometheus
  path: /actuator/prometheus
  interval: 15s
  portName: http
