fullnameOverride: world-master-service-prod

serviceAccount:
  create: true

agones:
  allocator:
    enabled: true

replicaCount: 1

image:
  repository: ghcr.io/donghun0508/world-master-service
  tag: ae690bda3f09c54bfd5c1a208094d5c50d534e5b
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

monitoring:
  enabled: true
  namespace: prometheus
  labels:
    release: prometheus
  path: /actuator/prometheus
  interval: 15s
  portName: http
