watchNamespaces:
  - kafka-prod

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  initialDelaySeconds: 600
  periodSeconds: 600
  failureThreshold: 100

readinessProbe:
  initialDelaySeconds: 600
  periodSeconds: 600
  failureThreshold: 100
