fullnameOverride: world-service-prod

deployment:
  enabled: false

agones:
  enabled: true
  fleet:
    replicas: 2
    scheduling: Packed
    strategy:
      type: RollingUpdate
    ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 7654
    annotations:
      octops.io/gameserver-ingress-mode: "domain"
      octops.io/gameserver-ingress-domain: "game.codecrew.site"
      octops.io/terminate-tls: "false"

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: "ghcr.io/donghun0508/world-service"
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "20m"
  limits:
    memory: "128Mi"
    cpu: "100m"
