fullnameOverride: world-service-prod

deployment:
  enabled: false

agones:
  enabled: true
  fleet:
    replicas: 1
    scheduling: Packed
    strategy:
      type: RollingUpdate
    ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 7654
    health:
      disabled: true
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 3
    annotations:
      octops.io/gameserver-ingress-mode: "domain"
      octops.io/gameserver-ingress-domain: "game.codecrew.site"
      octops.io/terminate-tls: "false"

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: "ghcr.io/donghun0508/world-service"
  tag: 3c5ab74ab7bccf6bc455bc3ec8f6833b2e6eab0b
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: SERVER_PORT
    value: "9090"
