fullnameOverride: world-service-prod

deployment:
  enabled: false

agones:
  enabled: true
  fleet:
    replicas: 1
    scheduling: Packed
    strategy:
      type: RollingUpdate
    ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 7654
    health:
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 3
    annotations:
      octops.io/gameserver-ingress-mode: "domain"
      octops.io/gameserver-ingress-domain: "game.codecrew.site"
      octops.io/terminate-tls: "false"

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: "ghcr.io/donghun0508/world-service"
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: SERVER_PORT
    value: "9090"
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0"
