fullnameOverride: world-service-prod

deployment:
  enabled: false

ingress:
  middleware:
    enabled: true


agones:
  enabled: true
  fleet:
    replicas: 1
    scheduling: Packed
    strategy:
      type: RollingUpdate
    ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 9090
        protocol: TCP
    health:
      initialDelaySeconds: 180
      periodSeconds: 8
      failureThreshold: 3
    annotations:
      octops.io/gameserver-ingress-mode: "path"
      octops.io/gameserver-ingress-domain: "world.codecrew.site"
      octops.io/gameserver-ingress-fqdn: "world.codecrew.site"
      octops.io/ingress-class-name: "traefik"
      octops.io/terminate-tls: "false"
      octops-traefik.ingress.kubernetes.io/router.middlewares: "world-service-prod-world-service-prod-strip-prefix@kubernetescrd"


imagePullSecrets:
  - name: ghcr-secret

image:
  repository: "ghcr.io/donghun0508/world-service"
  tag: ae690bda3f09c54bfd5c1a208094d5c50d534e5b
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: SERVER_PORT
    value: "9090"
