apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway
data:
  SERVER_PORT: "8080"
  MANAGEMENT_PORT: "8080"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"
