apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-gateway

resources:
  - configmap.yaml
  - sealedsecret.yaml

helmCharts:
  - name: service-helm
    releaseName: api-gateway
    repo: file://../../charts/service-helm
    valuesFile: prod.yaml
