apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "80.4.1"
    releaseName: prometheus
    namespace: prometheus
    valuesFile: values.yaml
