apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: "6.17.1"
    releaseName: promtail
    namespace: logging
    valuesFile: values.yaml
