apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service
  namespace: account-service
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/instance: account-service
data:
  SERVER_PORT: "8080"
  MANAGEMENT_PORT: "8080"