{{- if and .Values.ingress .Values.ingress.middleware .Values.ingress.middleware.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "service-helm.fullname" . }}-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefixRegex:
    regex:
      - ^/[^/]+
{{- end }}
