{{- if .Values.agones.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-sdk
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk
subjects:
  - kind: ServiceAccount
    name: agones-sdk
    namespace: {{ .Release.Namespace }}
{{- end }}
