{{- if and .Values.agones .Values.agones.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-sdk
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk
subjects:
  - kind: ServiceAccount
    name: agones-sdk
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.agones.allocator.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "service-helm.fullname" . }}-allocator
  labels:
    {{- include "service-helm.labels" . | nindent 4 }}
rules:
  - apiGroups: ["allocation.agones.dev"]
    resources: ["gameserverallocations"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "service-helm.fullname" . }}-allocator
  labels:
    {{- include "service-helm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "service-helm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "service-helm.fullname" . }}-allocator
{{- end }}
