{{- if .Values.agones.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-sdk
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-helm.labels" . | nindent 4 }}
{{- end }}
