{{- if (.Values.monitoring | default dict).enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "service-helm.fullname" . }}
  namespace: {{ .Values.monitoring.namespace | default "monitoring" }}
  labels:
    {{- toYaml (.Values.monitoring.labels | default dict) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "service-helm.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ default "http" .Values.monitoring.portName | quote }}
      path: {{ default "/actuator/prometheus" .Values.monitoring.path | quote }}
      interval: {{ default "15s" .Values.monitoring.interval | quote }}
  {{- end }}
