{{- if and .Values.serviceAccount .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-helm.labels" . | nindent 4 }}
{{- end }}

{{- if and .Values.agones .Values.agones.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-sdk
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-helm.labels" . | nindent 4 }}
{{- end }}
