apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  KC_PROXY: "edge"
  KC_HTTP_ENABLED: "true"
  KC_HTTP_PORT: "8080"
  KC_HOSTNAME_URL: "https://auth.codecrew.site"
  KC_HOSTNAME_ADMIN_URL: "https://auth.codecrew.site"
  KC_HOSTNAME_STRICT: "false"