apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  KC_PROXY_HEADERS: "xforwarded"
  KC_HTTP_ENABLED: "true"
  KC_HTTP_PORT: "8080"
  KC_HOSTNAME: "auth.codecrew.site"
  KC_HOSTNAME_STRICT: "false"