architecture: replication

auth:
  enabled: true
  existingSecret: redis-auth
  existingSecretPasswordKey: redis-password

metrics:
  enabled: false


master:
  replicaCount: 1

  persistence:
    enabled: false

  extraFlags:
    - "--appendonly"
    - "no"
    - "--save"
    - ""
    - "--maxmemory-policy"
    - "allkeys-lru"
    - "--maxmemory"
    - "256mb"

replica:
  replicaCount: 1

  persistence:
    enabled: false

  extraFlags:
    - "--replica-read-only"
    - "yes"
    - "--appendonly"
    - "no"
    - "--save"
    - ""
    - "--maxmemory-policy"
    - "allkeys-lru"
    - "--maxmemory"
    - "256mb"

  service:
    type: NodePort
    ports:
      redis: 6379
    nodePorts:
      redis: 30380

service:
  type: NodePort
  ports:
    redis: 6379
  nodePorts:
    redis: 30379

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
