apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/donghun0508/codecrew-gitops
        revision: main
        directories:
          - path: "services/*/envs/*"

  template:
    metadata:
      name: "{{index .path.segments 1}}-{{index .path.segments 3}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index .path.segments 1}}-{{index .path.segments 3}}"

      sources:
        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          path: "charts/service-helm"
          helm:
            releaseName: "{{index .path.segments 1}}"
            valueFiles:
              - "$values/{{.path.path}}/values.yaml"

        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          ref: values
          path: "{{.path.path}}"
          directory:
            recurse: true
            include: "{configmap.yaml,sealedsecret.yaml,sealedsecret-*.yaml}"
            exclude: "{values.yaml,secret.yaml}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
