apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/donghun0508/codecrew-gitops
        revision: main
        directories:
          - path: values/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"

      sources:
        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          path: charts/service-helm
          helm:
            releaseName: "{{path.basename}}"
            valueFiles:
              - $values/values/{{path.basename}}/prod.yaml

        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          ref: values
          path: values/{{path.basename}}
          directory:
            recurse: true
            include: "{configmap.yaml,sealedsecret.yaml,ghcr-sealedsecret.yaml}"
            exclude: "{prod.yaml,secret.yaml,kustomization.yaml}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
