apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/donghun0508/codecrew-gitops
        revision: main
        directories:
          - path: services/*/envs/*
  template:
    metadata:
      name: "{{path.segments[1]}}-{{path.segments[3]}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.segments[1]}}-{{path.segments[3]}}"

      sources:
        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          path: charts/service-helm
          helm:
            releaseName: "{{path.segments[1]}}"
            valueFiles:
              - $values/{{path.path}}/values.yaml

        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          ref: values
          path: {{path.path}}
          directory:
            recurse: true
            include: "{configmap.yaml,sealedsecret.yaml,sealedsecret-*.yaml}"
            # exclude values.yaml as it is used in the helm source above
            exclude: "{values.yaml,secret.yaml}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true